### ISSUE TITLE
Startup Too Verbose

### ISSUE THREAD

**Issue by creichert** [CodyReichert/qi#2]
The init `.qi/init.lisp` script seems to have very verbose output on each load of sbcl. It doesn't affect the functionality but makes it hard to read what's going on

**Comment by CodyReichert** [comment]
I did some work on this that will load the already compiled ASDF fasl if it's available (instead of recompiling ASDF every time): https://github.com/CodyReichert/qi/commit/9aa082d850973a0121291c99c0e12eb78e1c4fa8

There's one more step, which is to do the same thing with the Qi fasl. The output is shorter and SBCL startup time is faster, but it looks like Qi is still being compiled every time.

**Comment by CodyReichert** [comment]
Although there's still some compilation output when building a project - the verbose output on startup is cleared up now.
